#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#     ||          ____  _ __
#  +------+      / __ )(_) /_______________ _____  ___
#  | 0xBC |     / __  / / __/ ___/ ___/ __ `/_  / / _ \
#  +------+    / /_/ / / /_/ /__/ /  / /_/ / / /_/  __/
#   ||  ||    /_____/_/\__/\___/_/   \__,_/ /___/\___/
#
#  Copyright (C) 2017 Bitcraze AB
#
#  Crazyflie Python Library
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
"""
Script modificado para mantener al Crazyflie centrado en un pasillo,
usando Flow y Multi-ranger decks. Evita obstáculos adelante/atrás
y centra lateralmente según la distancia izquierda/derecha.
"""

import logging
import sys
import time

import cflib.crtp
from cflib.crazyflie import Crazyflie
from cflib.crazyflie.syncCrazyflie import SyncCrazyflie
from cflib.positioning.motion_commander import MotionCommander
from cflib.utils import uri_helper
from cflib.utils.multiranger import Multiranger

URI = uri_helper.uri_from_env(default='radio://0/80/2M/E7E7E7E7AA')

if len(sys.argv) > 1:
    URI = sys.argv[1]

# Solo mostrar errores
logging.basicConfig(level=logging.ERROR)


def is_close(range):
    MIN_DISTANCE = 0.2  # m
    if range is None:
        return False
    else:
        return range < MIN_DISTANCE


if __name__ == '__main__':
    cflib.crtp.init_drivers()

    cf = Crazyflie(rw_cache='./cache')
    with SyncCrazyflie(URI, cf=cf) as scf:
        scf.cf.platform.send_arming_request(True)
        time.sleep(1.0)

        with MotionCommander(scf) as motion_commander:
            with Multiranger(scf) as multiranger:
                keep_flying = True

                while keep_flying:
                    VELOCITY = 0.5
                    KP = 1.0  # ganancia proporcional (ajustar según comportamiento)
                    velocity_x = 0.0
                    velocity_y = 0.0

                    # Centrarse en el pasillo usando control proporcional
                    # error = left - right. Si error>0 => mover izquierda (velocity_y negativo)
                    if multiranger.left is not None and multiranger.right is not None:
                        error = multiranger.left - multiranger.right
                        # deadband pequeña para evitar oscilar por ruido (1 cm)
                        if abs(error) > 0.01:
                            # proporcional: invertir signo para que error>0 -> mover izquierda
                            velocity_y = -KP * error
                            # limitar velocidad máxima a `VELOCITY` por seguridad
                            if velocity_y > VELOCITY:
                                velocity_y = VELOCITY
                            elif velocity_y < -VELOCITY:
                                velocity_y = -VELOCITY

                    # Comprobar sensor superior (mano encima)
                    if is_close(multiranger.up):
                        print('Hand detected above, stopping demo')
                        keep_flying = False

                    motion_commander.start_linear_motion(
                        velocity_x, velocity_y, 0
                    )

                    time.sleep(0.1)

            print('Demo terminated!')
